import { app } from "/scripts/app.js";

// Keep Python input names and serialized combo values unchanged so workflows
// created before the Chinese UI extension remain fully compatible.
export const WIDGET_LABELS = {
    audio_file: "音频文件",
    start_time: "开始时间（秒）",
    end_time: "结束时间（秒）",
    image: "图像",
    images: "图像批次",
    precision: "精度",
    torch_compile: "Torch编译",
    ds_factor: "DS因子",
    interpolation_factor: "补帧因子",
    output_flows: "输出流量",
    flow_tensors: "流动张量",
    image_text: "文字纹理图像",
    image_background: "背景图像",
    image_layer: "前景图层",
    background: "背景图像",
    foreground: "前景图像",
    clean_background: "干净背景图像",
    source_image: "源图像",
    reference_image: "参考图像",
    displacement_image: "位移图像",
    mask: "作用区域遮罩",
    layer_mask: "图层遮罩",
    text_mask: "文字遮罩",
    region_mask: "文字区域遮罩",
    path_mask: "文字路径遮罩",
    text: "文字内容",
    sample_text: "预览文字",
    font_name: "字体",
    font_scope: "字体范围",
    font_size: "字号",
    sample_font_size: "预览字号",
    min_font_size: "最小字号",
    max_font_size: "最大字号",
    font_color: "文字颜色",
    font_color_hex: "文字颜色（HEX）",
    text_color: "预览文字颜色",
    text_color_hex: "预览文字颜色（HEX）",
    background_color: "背景颜色",
    background_color_hex: "背景颜色（HEX）",
    image_width: "画布宽度",
    image_height: "画布高度",
    align: "垂直对齐",
    vertical_align: "垂直对齐",
    justify: "水平对齐",
    margins: "边距",
    x_margin: "水平边距",
    y_margin: "垂直边距",
    padding: "区域内边距",
    line_spacing: "行距",
    letter_spacing: "字距",
    position_x: "水平偏移",
    position_y: "垂直偏移",
    rotation: "旋转角度",
    rotation_angle: "旋转角度",
    rotation_options: "旋转中心",
    edge_expand: "边缘扩张",
    edge_feather: "边缘羽化",
    opacity: "整体透明度",
    position: "位置",
    size_percent: "字号比例",
    max_width_percent: "最大宽度比例",
    x_margin_percent: "水平边距比例",
    y_margin_percent: "垂直边距比例",
    text_opacity: "文字填充透明度",
    effect_preset: "文字特效预设",
    fill_mode: "填充方式",
    gradient_color: "渐变结束颜色",
    gradient_color_hex: "渐变结束颜色（HEX）",
    gradient_angle: "渐变角度",
    outline_width: "第一层外描边宽度",
    outline_color: "第一层外描边颜色",
    outline_color_hex: "第一层外描边颜色（HEX）",
    outer_outline2_width: "第二层外描边宽度",
    outer_outline2_color: "第二层外描边颜色",
    outer_outline2_color_hex: "第二层外描边颜色（HEX）",
    outline_gap: "外描边间距",
    inner_outline_width: "内描边宽度",
    inner_outline_color: "内描边颜色",
    inner_outline_color_hex: "内描边颜色（HEX）",
    highlight_offset_x: "高光水平偏移",
    highlight_offset_y: "高光垂直偏移",
    highlight_strength: "高光强度",
    glow_radius: "发光半径",
    glow_strength: "发光强度",
    glow_color: "发光颜色",
    glow_color_hex: "发光颜色（HEX）",
    shadow_offset_x: "阴影水平偏移",
    shadow_offset_y: "阴影垂直偏移",
    shadow_blur: "阴影模糊",
    shadow_opacity: "阴影透明度",
    shadow_color: "阴影颜色",
    shadow_color_hex: "阴影颜色（HEX）",
    emboss_depth: "浮雕深度",
    extrude_depth: "立体挤出深度",
    extrude_offset_x: "挤出水平偏移",
    extrude_offset_y: "挤出垂直偏移",
    extrude_color: "挤出颜色",
    extrude_color_hex: "挤出颜色（HEX）",
    blend_mode: "混合模式",
    split_mode: "拆分方式",
    include_whitespace: "包含空白字符",
    max_lines: "最大行数",
    overflow: "溢出处理",
    page: "页码",
    page_size: "每页字体数",
    columns: "每行列数",
    cell_width: "单格宽度",
    cell_height: "单格高度",
    animation: "动画方式",
    unit: "动画单位",
    frame_count: "动画帧数",
    stagger_frames: "单位错开帧数",
    hold_frames: "结尾停留帧数",
    direction: "方向",
    transform: "变形方式",
    frequency: "波形频率",
    start_offset: "路径起始偏移",
    path_offset: "路径法线偏移",
    reverse: "反向排列",
    orientation: "文字朝向",
    filename_prefix: "文件名前缀",
    fps: "每秒帧数",
    loop: "循环次数",
    pingpong: "往返播放",
    optimize: "优化文件体积",
    compression_preset: "压缩预设",
    resize_scale: "缩放比例",
    max_colors: "最大颜色数",
    frame_step: "保留帧间隔",
    dither: "抖动方式",
    preset: "效果预设",
    strength: "效果强度",
    antialias: "抗锯齿",
    auto_white_balance: "自动白平衡",
    white_balance_method: "白平衡方法",
    neutral_strictness: "中性取样严格度",
    white_balance_strength: "白平衡强度",
    max_white_balance_ev: "白平衡最大档位",
    auto_exposure: "自动曝光",
    target_midtone: "中灰目标",
    max_exposure_ev: "曝光最大档位",
    highlight_protection: "高光保护",
    confidence_threshold: "置信度阈值",
    analysis_mask: "分析遮罩",
    diagnostic_report: "诊断报告",
    exposure: "曝光",
    contrast: "对比度",
    highlights: "高光",
    shadows: "阴影",
    whites: "白色色阶",
    blacks: "黑色色阶",
    light_sensation: "光感",
    temperature: "色温",
    tint: "色调",
    saturation: "饱和度",
    vibrance: "自然饱和度",
    clarity: "清晰度",
    texture: "纹理",
    dehaze: "去朦胧",
    sharpen: "锐化",
    luminance_denoise: "亮度降噪",
    color_denoise: "颜色降噪",
    grain: "颗粒",
    fade: "褪色",
    color_range: "HSL 颜色范围",
    hue_shift: "色相",
    lightness: "亮度",
    seed: "随机种子",
    color_mode: "分色模式",
    palette_text: "调色板颜色",
    dot_size: "网点大小",
    screen_angle: "网屏角度",
    registration_shift: "套印偏移",
    ink_bleed: "油墨扩散",
    paper_grain: "纸张颗粒",
    color_levels: "颜色层级",
    line_width: "线稿宽度",
    line_strength: "线稿强度",
    line_threshold: "线稿阈值",
    shadow_threshold: "阴影阈值",
    shadow_halftone: "阴影网点化",
    segments: "镜像分区数",
    center_x: "中心水平位置",
    center_y: "中心垂直位置",
    zoom: "缩放",
    mirror: "镜像扇区",
    seam_softness: "接缝柔化",
    pixel_size: "像素块大小",
    palette_mode: "调色板模式",
    custom_palette: "自定义调色板",
    outline_strength: "像素描边强度",
    outline_threshold: "像素描边阈值",
    mode: "效果模式",
    amount: "变形量",
    scale: "纹理尺度",
    angle: "方向角度",
    blur: "模糊程度",
    chromatic_aberration: "色差强度",
    roughness: "粗糙度",
    rgb_shift: "RGB 通道偏移",
    block_count: "故障块数量",
    block_height: "故障块高度",
    scanline_strength: "扫描线强度",
    sort_threshold: "像素排序阈值",
    noise_strength: "噪点强度",
    effect: "动态滤镜",
    frames: "生成帧数",
    cycles: "循环周期数",
    amplitude: "动画幅度",
    seamless_loop: "无缝循环",
    sam_mask: "SAM 前景遮罩",
    key_color: "抠除颜色",
    custom_color: "自定义颜色（HEX）",
    color_tolerance: "颜色容差",
    color_softness: "颜色柔化",
    spill_suppression: "溢色抑制",
    grow_shrink: "遮罩扩张/收缩",
    edge_feather: "边缘羽化",
    invert_mask: "反转遮罩",
    model: "AI 模型",
    provider: "运行设备",
    value: "输入",
    delay_ms: "等待时间（毫秒）",
    size_mode: "图层尺寸模式",
    shape_mode: "边缘形状",
    shape_amount: "形状尺寸",
    shape_strength: "形状强度",
    transition_mode: "过渡方式",
    transition_strength: "过渡强度",
    material_mode: "材质效果",
    material_strength: "材质强度",
    depth_mode: "深度模式",
    depth_strength: "深度强度",
    edge_width: "边缘宽度",
    edge_color: "边缘颜色",
    edge_color_hex: "边缘颜色（HEX）",
    detail_scale: "细节尺度",
    irregularity: "不规则程度",
    background_wrap: "背景光包裹",
    background_blur: "背景模糊",
    depth_offset: "深度偏移",
    depth_offset_x: "深度水平偏移",
    depth_offset_y: "深度垂直偏移",
    tilt_x: "水平倾斜",
    tilt_y: "垂直倾斜",
    flip_h: "水平翻转",
    flip_v: "垂直翻转",
    blend_if_data: "Blend If 设置",
    curve_data: "曲线数据",
    interpolation: "插值方式",
    method: "处理方法",
    channel_mode: "通道模式",
    protect_luminance: "保护亮度",
    preserve_luminance: "保留亮度",
    protect_skin: "保护肤色",
    saturation_limit: "饱和度上限",
    saturation_compression: "饱和度压缩",
    highlight_tint: "高光染色",
    contrast_softening: "对比度柔化",
    toe: "暗部趾部",
    shoulder: "高光肩部",
    gradient_data: "渐变数据",
    lut_path: "LUT 文件路径",
    lut_file: "LUT 文件",
    lut_data: "LUT 数据",
    preview_strength: "预览强度",
    preview_image_file: "手动预览图片",
    highlight_threshold: "高光阈值",
    softness: "阈值柔度",
    radius: "参考半径",
    ring_width: "环宽",
    tail_decay: "长尾衰减",
    spread: "扩散增益",
    red_orange_ratio: "红橙比例",
    rich_text: "富文本内容",
    font: "默认字体",
    max_width: "最大排版宽度",
    x: "水平位置",
    y: "垂直位置",
    default_color: "默认文字颜色",
    inline_bg: "显示行内背景",
    sort_by: "排序依据",
    low: "低阈值",
    high: "高阈值",
    span_limit: "最大连续段长度",
    width: "遮罩宽度",
    height: "遮罩高度",
    path_data: "路径数据",
    stroke_width: "路径线宽",
    masks: "实例遮罩批次",
    merge_mode: "合并方式",
    threshold: "二值阈值",
    grow: "扩张/收缩",
    feather: "羽化",
    invert: "反转",
    image_subject: "主体图像",
    image_texture: "纹理图像",
    texture_fit: "纹理适配",
    exposure_balance: "曝光平衡",
    subject_mask: "主体遮罩",
    image_foreground: "前景图像",
    color_match: "颜色匹配",
    edge_shrink: "边缘收缩",
    clone_mode: "贴合模式",
    foreground_mask: "前景遮罩",
    color_space: "色彩空间",
    denoise: "降噪",
    black_point: "黑场点",
    white_point: "白场点",
    edge_contrast: "边缘对比度",
    fill_holes: "填补孔洞",
    detail_recovery: "细节恢复",
    despill_color: "去溢色基准颜色",
    despill_color_hex: "去溢色颜色（HEX）",
    despill_strength: "去溢色强度",
    wrap_width: "光线包裹宽度",
    color_bleed: "背景颜色渗入",
    inner_ratio: "向内扩展比例",
    depth_a: "深度图 A",
    depth_b: "深度图 B",
    red_expression: "红通道表达式",
    green_expression: "绿通道表达式",
    blue_expression: "蓝通道表达式",
    alpha_expression: "透明通道表达式",
    channel_x: "水平位移通道",
    channel_y: "垂直位移通道",
    strength_x: "水平位移强度",
    strength_y: "垂直位移强度",
    neutral: "位移中性值",
    image_structure: "结构图像",
    image_detail: "细节图像",
    low_frequency_source: "低频来源",
    high_frequency_source: "高频来源",
    detail_gain: "细节增益",
    detail_restore: "细节还原",
    color_source: "颜色来源",
    image_source: "源图像",
    image_reference: "参考图像",
    smooth_scale: "光照平滑尺度",
    exposure_range: "曝光范围",
    color_preservation: "颜色保留",
    detail_protection: "细节保护",
    source_mask: "源图遮罩",
    reference_mask: "参考图遮罩",
    output_mode: "输出方式",
    target_width: "目标宽度",
    target_height: "目标高度",
    composition_tightness: "构图跟随强度",
    subject_position: "主体构图位置",
    edge_safety: "边缘安全区",
    model_quality: "模型质量",
    device: "运行设备",
    batch: "批次",
    rows: "拼贴行数",
    canvas_width: "画布宽度",
    canvas_height: "画布高度",
    margin: "画布边距",
    spacing: "单元间隔",
    layout: "分镜模板",
    page_margin: "页面边距",
    gutter: "画格间距",
    border_width: "边框宽度",
    border_color: "边框颜色",
    empty_fill: "空格填充",
    panel_data: "分镜配置",
    enabled: "启用对话框",
    default_font: "默认字体",
    bubble_data: "对话框配置",
    panel_mask: "画格遮罩",
    border_mask: "画框线遮罩",
    bubble_mask: "对话框遮罩",
    fit_mode: "图片适配",
    corner_radius: "圆角半径",
    shadow: "阴影大小",
    style: "样式",
    density: "密度",
    left: "左边框",
    right: "右边框",
    top: "上边框",
    bottom: "下边框",
    bottom_extra: "底部额外留白",
    frame_color: "相框颜色",
    accent_color: "装饰颜色",
    length: "光带长度",
    thickness: "光带厚度",
    color: "效果颜色",
    target_color: "目标颜色",
    ghost_count: "鬼影数量",
    ghost_spacing: "鬼影间距",
    intensity: "亮度强度",
    count: "散景数量",
    shape: "光圈形状",
    brightness: "散景亮度",
    distortion: "径向畸变",
    tangential_x: "水平切向偏移",
    tangential_y: "垂直切向偏移",
    vignette: "暗角",
    edge_softness: "边缘柔化",
    boundary: "边界处理",
    image_moving: "待对齐图像",
    moving_mask: "待对齐图遮罩",
    image_a: "图像 A",
    image_b: "图像 B",
    mask_a: "遮罩 A",
    mask_b: "遮罩 B",
    operation: "运算方式",
    resize_mode: "尺寸基准",
    accuracy: "配准精度",
    max_iterations: "最大迭代次数",
    blend_mask: "融合遮罩",
    mask_softness: "遮罩柔化",
    linear_light: "线性光处理",
    color_balance: "颜色平衡",
    contact_hardness: "接触区硬度",
    distance_blur: "远端扩散",
    ambient_occlusion: "环境遮蔽",
    repair_mask: "修复区域遮罩",
    mask_expand: "修复区域扩张",
    mask_feather: "修复边缘羽化",
    color_protection: "颜色保护",
    selection: "索引选择表达式",
    levels: "融合层级数",
    strip_whitespace: "清理首尾空白",
    remove_empty: "移除空项目",
    separator: "分隔符",
    step: "抽取步长",
    repeat: "重复次数",
    out_of_range: "越界处理",
    round_to_multiple: "尺寸倍数",
    allow_upscale: "允许放大",
    anchor: "画布锚点",
    resampling: "缩放插值",
    view: "监看视图",
    signal_range: "信号范围",
    transfer: "传递函数",
    sample_step: "采样步长",
    hue_center: "色相中心",
    hue_width: "色相范围",
    hue_softness: "色相柔化",
    saturation_min: "最低饱和度",
    saturation_max: "最高饱和度",
    saturation_softness: "饱和度柔化",
    luminance_min: "最低亮度",
    luminance_max: "最高亮度",
    luminance_softness: "亮度柔化",
    clean_black: "清理黑场",
    clean_white: "清理白场",
    limit_mask: "限定范围遮罩",
    depth_map: "深度图",
    depth_direction: "深度方向",
    focus_depth: "焦点深度",
    focus_width: "清晰范围",
    near_blur: "近景虚化",
    far_blur: "远景虚化",
    aperture_shape: "光圈形状",
    aperture_rotation: "光圈旋转",
    highlight_boost: "失焦高光增强",
    cat_eye: "猫眼散景",
    hue_range: "色相范围",
    save_metadata: "保存工作流元数据",
    latent: "潜空间",
    model_format: "模型格式",
    half_precision: "半精度运行",
    clip: "CLIP",
    lora_name: "LoRA文件",
    generation_mode: "强度生成方式",
    start_strength: "起始强度",
    end_strength: "结束强度",
    strength_step: "强度步长",
    custom_strengths: "自定义强度列表",
    clip_strength_mode: "CLIP强度模式",
    fixed_clip_strength: "CLIP固定强度",
    max_tests: "最大测试数量",
};

export const SLOT_LABELS = {
    audio: "裁剪音频",
    duration: "实际时长",
    start_time: "实际开始时间",
    end_time: "实际结束时间",
    sample_rate: "采样率",
    channels: "声道数",
    image_a: "图像 A",
    image_b: "图像 B",
    image: "图像",
    images: "图像批次",
    image_text: "文字纹理图像",
    image_background: "背景图像",
    background: "背景图像",
    mask: "遮罩",
    path_mask: "路径遮罩",
    region_mask: "区域遮罩",
    frames: "动画帧",
    show_help: "帮助",
    text_mask: "文字遮罩",
    unit_mask: "分单位遮罩",
    effect_mask: "效果遮罩",
    ink_texture: "油墨纹理",
    line_mask: "线稿遮罩",
    shadow_mask: "阴影遮罩",
    palette_image: "调色板预览",
    displacement_map: "位移图",
    sam_mask: "SAM 前景遮罩",
    foreground: "抠像前景",
    foreground_mask: "前景遮罩",
    background_mask: "背景遮罩",
    font_name: "字体名称",
    image_layer: "前景图层",
    layer_mask: "图层遮罩",
    clean_background: "干净背景图像",
    source_image: "源图像",
    reference_image: "参考图像",
    displacement_image: "位移图像",
    depth_a: "深度图 A",
    depth_b: "深度图 B",
    blend_mask: "融合遮罩",
    transformed_mask: "变换后遮罩",
    detail_image: "细节图",
    light_map: "光照图",
    crop_mask: "裁切区域遮罩",
    saliency_mask: "显著性遮罩",
    layout_mask: "拼贴区域遮罩",
    frame_mask: "相框遮罩",
    flare_mask: "耀斑遮罩",
    bokeh_mask: "散景遮罩",
    composite_mask: "实际合成遮罩",
    halation_mask: "卤化光晕遮罩",
    gradient_preview: "渐变预览",
    lut_data: "LUT 数据",
    merged_mask: "合并遮罩",
    instance_count: "实例数量",
    path_data: "路径数据",
    aligned_image: "对齐后图像",
    valid_mask: "有效区域遮罩",
    difference_image: "差异图",
    transform_data: "变换数据",
    effective_mask: "实际融合遮罩",
    seam_map: "接缝诊断图",
    contact_mask: "接触区域遮罩",
    inverse_mask: "反相遮罩",
    overlap_mask: "重叠区域遮罩",
    repaired_mask: "实际修复遮罩",
    content_mask: "有效内容遮罩",
    output_mask: "输出遮罩",
    index_map: "原始索引映射",
    analysis_image: "分析画面",
    warning_mask: "警告区域遮罩",
    statistics_json: "统计数据",
    qualified_image: "限定区域图像",
    qualifier_mask: "限定器遮罩",
    matte_preview: "遮罩预览",
    coc_map: "弥散圈图",
    focus_mask: "焦内遮罩",
    correction_mask: "校色遮罩",
    diffusion_mask: "扩散效果遮罩",
    compressed_mask: "压缩区域遮罩",
    edge_mask: "边缘遮罩",
    wrapped_foreground: "光线包裹前景",
    wrap_mask: "光线包裹遮罩",
    selection_mask: "深度选择遮罩",
    depth_difference: "深度差异图",
    transformed_layer: "变换后图层",
    alpha_mask: "透明通道遮罩",
    affected_mask: "受影响区域遮罩",
    glitch_mask: "故障效果遮罩",
    distortion_map: "畸变图",
    filename: "文件名",
    help_document: "帮助文档",
    selected_item: "选中项目",
    selected_index: "选中编号",
    latent: "潜空间",
    model: "模型",
    models: "模型批次",
    clip: "CLIP",
    clips: "CLIP批次",
    strengths: "强度批次",
    labels: "标签批次",
    item_count: "项目数量",
};

const EXCEL_NODE_IDS = new Set([
    "TUT_LoadExcel",
    "TUT_ReadExcelBatch",
    "TUT_ReadExcelMerged",
    "TUT_ReadExcelSingleLine",
]);

// Excel uses several generic internal names (for example `orientation` and
// `index`) whose best Chinese labels differ from nodes in other categories.
// Keep these translations node-scoped so the text-path `orientation` widget
// continues to display as "文字朝向".
const EXCEL_LABELS = {
    excel_path: "Excel文件",
    sheet_name: "工作表",
    cell_range: "读取范围",
    formula_mode: "公式模式",
    excel_data: "Excel数据",
    orientation: "组织方式",
    skip_rows: "跳过前N行",
    skip_columns: "跳过前N列",
    cell_separator: "单元格分隔符",
    group_separator: "组间分隔符",
    max_items: "读取数量上限",
    read_direction: "读取方向",
    index: "编号",
    skip_items: "跳过前N项",
    merge_separator: "合并分隔符",
    text_items: "文本批次",
    text: "合并文本",
    sheet_names: "工作表列表",
    selected_sheet: "当前工作表",
    item_count: "项目数量",
    row_count: "行数",
    column_count: "列数",
};

const COLOR_LABELS = {
    custom: "自定义",
    white: "白色",
    black: "黑色",
    red: "红色",
    green: "绿色",
    blue: "蓝色",
    yellow: "黄色",
    cyan: "青色",
    magenta: "品红",
    orange: "橙色",
    purple: "紫色",
    pink: "粉色",
    gray: "灰色",
    gold: "金色",
    silver: "银色",
    navy: "深蓝",
    teal: "蓝绿色",
};

export const OPTION_LABELS = {
    align: {
        left: "左对齐",
        right: "右对齐",
        center: "居中",
        top: "顶部",
        bottom: "底部",
        "top left": "左上",
        "top center": "顶部居中",
        "top right": "右上",
        "bottom left": "左下",
        "bottom center": "底部居中",
        "bottom right": "右下",
    },
    vertical_align: { center: "居中", top: "顶部", bottom: "底部" },
    justify: { center: "居中", left: "左对齐", right: "右对齐" },
    rotation_options: { "text center": "文字中心", "image center": "画布中心" },
    effect_preset: {
        none: "无",
        custom: "自定义",
        outline: "描边",
        shadow: "阴影",
        glow: "外发光",
        neon: "霓虹",
        gradient: "渐变",
        emboss: "浮雕",
        extrude: "立体挤出",
    },
    fill_mode: {
        solid: "纯色",
        linear_gradient: "线性渐变",
        radial_gradient: "径向渐变",
        image: "图像纹理",
    },
    blend_mode: {
        normal: "正常",
        multiply: "正片叠底",
        screen: "滤色",
        overlay: "叠加",
        darken: "变暗",
        color_burn: "颜色加深",
        linear_burn: "线性加深",
        lighten: "变亮",
        color_dodge: "颜色减淡",
        linear_dodge: "线性减淡",
        soft_light: "柔光",
        hard_light: "强光",
        vivid_light: "亮光",
        linear_light: "线性光",
        pin_light: "点光",
        hard_mix: "实色混合",
        difference: "差值",
        exclusion: "排除",
        subtract: "减去",
        divide: "划分",
        hue: "色相",
        saturation: "饱和度",
        color: "颜色",
        luminosity: "明度",
    },
    dither: {
        "Floyd-Steinberg": "Floyd-Steinberg 误差扩散",
        "Bayer 2x2": "Bayer 2×2 有序抖动",
        "Bayer 4x4": "Bayer 4×4 有序抖动",
    },
    preset: {
        Risograph: "孔版印刷（Risograph）",
        "Game Boy": "Game Boy 掌机",
        "16-bit": "16 位像素风格",
    },
    palette_mode: {
        "Game Boy": "Game Boy 掌机",
        "16-bit": "16 位像素风格",
    },
    provider: { auto: "自动", cuda: "CUDA 显卡", cpu: "CPU" },
    device: { auto: "自动", cuda: "CUDA 显卡", cpu: "CPU" },
    despill_color: { green: "绿色", blue: "蓝色", custom: "自定义" },
    clone_mode: {
        normal: "普通克隆",
        mixed: "混合克隆",
        monochrome: "单色克隆",
    },
    fit_mode: {
        cover: "覆盖画布",
        contain: "完整适配",
        stretch: "拉伸填充",
    },
    model_quality: { u2netp: "轻量模型（u2netp）", u2net: "高质量模型（u2net）" },
};

const COLOR_WIDGETS = new Set([
    "font_color", "gradient_color", "outline_color", "outer_outline2_color",
    "inner_outline_color", "glow_color", "shadow_color", "extrude_color",
    "background_color", "text_color", "key_color",
]);

export function optionLabel(widgetName, value) {
    const text = String(value ?? "");
    if (widgetName === "font_name") {
        if (text === "default/Pillow") return "Pillow 默认字体";
        if (text.startsWith("builtin/")) return `插件字体/${text.slice(8)}`;
        if (text.startsWith("system/")) return `系统字体/${text.slice(7)}`;
    }
    const specific = OPTION_LABELS[widgetName]?.[text];
    if (specific) return specific;
    if (COLOR_WIDGETS.has(widgetName) && COLOR_LABELS[text]) return COLOR_LABELS[text];
    return text;
}

function localizeWidget(widget) {
    if (!widget || widget.__tutChineseLocalized) return;
    widget.__tutChineseLocalized = true;
    widget.label = WIDGET_LABELS[widget.name] ?? widget.label ?? widget.name;

    if (widget.options?.values) {
        const values = widget.options.values;
        const rawValues = typeof values === "function"
            ? null
            : (Array.isArray(values) ? values : Object.keys(values));
        const needsTranslatedOptions = rawValues?.some(
            (value) => optionLabel(widget.name, value) !== String(value ?? ""),
        );
        // Do not attach getOptionLabel when every stored value is already the
        // desired Chinese label. In this Node 1.0 frontend, that optional path
        // can display a context menu whose selected item is not written back.
        if (!needsTranslatedOptions) return;
        const previousGetOptionLabel = widget.options.getOptionLabel;
        // Node 1.0 keeps the original options object when it creates the combo
        // menu. Replacing that object makes arrow cycling work while menu
        // selection writes to a stale reference. Preserve the object identity.
        widget.options.getOptionLabel = function (value) {
            const translated = optionLabel(widget.name, value);
            if (translated !== String(value ?? "")) return translated;
            return previousGetOptionLabel?.call(this, value) ?? value;
        };
    }
}

function localizeSlot(slot) {
    if (!slot) return;
    slot.label = SLOT_LABELS[slot.name] ?? WIDGET_LABELS[slot.name] ?? slot.label ?? slot.name;
}

export function localizeNode(node) {
    const comfyClass = String(node?.comfyClass ?? node?.type ?? "");
    if (!comfyClass.startsWith("TUT_")) return false;
    node.widgets?.forEach(localizeWidget);
    if (EXCEL_NODE_IDS.has(comfyClass)) {
        node.widgets?.forEach((widget) => {
            if (EXCEL_LABELS[widget?.name]) widget.label = EXCEL_LABELS[widget.name];
        });
    }
    if (comfyClass === "TUT_RichTextOverlay") {
        const align = node.widgets?.find((widget) => widget.name === "align");
        if (align) align.label = "水平对齐";
    }
    if (comfyClass === "TUT_BasicTone") {
        const brightness = node.widgets?.find((widget) => widget.name === "brightness");
        if (brightness) brightness.label = "亮度";
    }
    if (comfyClass === "TUT_GIMMVFIInterpolate") {
        const model = node.widgets?.find((widget) => widget.name === "model");
        if (model) model.label = "GIMM-VFI 模型";
    }
    node.inputs?.forEach(localizeSlot);
    node.outputs?.forEach(localizeSlot);
    if (EXCEL_NODE_IDS.has(comfyClass)) {
        node.inputs?.forEach((slot) => {
            if (EXCEL_LABELS[slot?.name]) slot.label = EXCEL_LABELS[slot.name];
        });
        node.outputs?.forEach((slot) => {
            if (EXCEL_LABELS[slot?.name]) slot.label = EXCEL_LABELS[slot.name];
        });
    }
    node.setDirtyCanvas?.(true, true);
    return true;
}

app.registerExtension({
    name: "TUT_Nodes.ChineseUI",
    nodeCreated(node) {
        localizeNode(node);
    },
});
